language: python

sudo: false

env:
    - TOX_ENV=py27-djangomaster
    - TOX_ENV=py34-djangomaster
    - TOX_ENV=py34-django18
    - TOX_ENV=py27-django18
    - TOX_ENV=py34-django17
    - TOX_ENV=py27-django17
    - TOX_ENV=coverage_combine
    - TOX_ENV=docs

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=coverage_combine
    - env: TOX_ENV=docs
    - env: TOX_ENV=py27-djangomaster
    - env: TOX_ENV=py34-djangomaster

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

install:
  - pip install tox

script:
    - tox -e $TOX_ENV

after_success:
    - coveralls

notifications:
    email:
        - alainivars@gmail.com
